#!/bin/tcsh

module purge PrgEnv-intel
module load PrgEnv-gnu openmpi
echo ""
echo "#--------------------- compling --------------------#"
make
echo ""
echo "#--------------------- cleaning --------------------#"
make clean
echo ""