#!/bin/tcsh

#SBATCH -J test_mpi
#SBATCH -o log.%j
#SBATCH --qos regular       
#SBATCH -N 1            
#SBATCH -n 32
#SBATCH -t 00:10:00 
##SBATCH -A m2407 #MR
#SBATCH -A m3757  #CSR
#SBATCH --constraint=haswell

module purge PrgEnv-intel
module load PrgEnv-gnu openmpi
echo ""
echo "#--------------------- compling --------------------#"
make
echo ""
echo "#--------------------- cleaning --------------------#"
make clean
echo ""

set verbose
setenv OMP_NUM_THREADS 1

srun ./test_mpi
exit
