#!/bin/tcsh
#SBATCH -J h3d
#SBATCH -o log.%j
#SBATCH -p normal
#SBATCH -N 2
#SBATCH -n 112
#SBATCH -t 01:00:00
#SBATCH -A PHY20020     

date

module purge
module load gcc/9.1.0 impi/19.0.9
make clean
make
make clean 

set verbose
setenv OMP_NUM_THREADS 1

setenv DATA_DIRECTORY ./data
setenv RESTART_DIRECTORY ./restart
setenv INPUT_DIRECTORY ./
setenv SOURCE_DIRECTORY ./
mkdir -p $DATA_DIRECTORY
mkdir -p $RESTART_DIRECTORY
cp input.dat $DATA_DIRECTORY/

ibrun -np $SLURM_NTASKS $SOURCE_DIRECTORY/3dh 
echo 'Done'
