! define waves that could be launched/loaded into the simulation domain

module m_wave
  implicit none 

  contains 

  subroutine init_wave
    integer*8 :: ibp1, ibp2, i, remake, field_subcycle
    real*8 :: rxe, rye, rze, fxe, fye, fze, dtxi, dtyi, dtzi, &
              x_p, y_p, z_p, x_p_logical, y_p_logical, z_p_logical, &
              r_c, q_p, dtsav
    integer*8 :: ip, ipb1, ipb2, is, ixe, iye, ize, j, k
    real*8 :: vxa, vya, vza, vmag, th, ranval(4)
    real*8 :: x_pos, y_pos, z_pos, B0, VA, dB0, mi
    real*8 :: bx_, by_, bz_, ex_, ey_, ez_
    real*8 :: kx, ky, kz, kxmin, kymin, kzmin, dvx_, dvy_, dvz_, sin_factor
    real*8 :: w1e, w2e, w3e, w4e, w5e, w6e, w7e, w8e
    real*8 :: vix1, viy1, viz1, vix2, viy2, viz2, vix3, viy3, viz3, vix4, viy4, viz4, &
              vix5, viy5, viz5, vix6, viy6, viz6, vix7, viy7, viz7, vix8, viy8, viz8
    integer :: ixep1,iyep1,izep1
    integer :: tag, tag0

    real*8 :: loaded_percentage, print_percentage
    integer :: seed_size
    integer, allocatable :: seed(:)

    dtxi = one/meshX%dt ! dtxi=nx
    dtyi = one/meshY%dt ! dtyi=ny
    dtzi = one/meshZ%dt ! dtzi=nz

    ! initialize the random number generator with a different seed for different processors
    call random_seed(size=seed_size) ! obtain seed size
    allocate(seed(seed_size))
    ! VR: arbirary, but reproducible numbers for phases
    if (myid==0) then
      ! method 1: with a given seed
      seed = 31415  
      ! method 2: with seed generated by system
      ! call random_seed() 
      ! call random_seed(get=seed)
    endif
    call MPI_BCAST(seed, seed_size, MPI_INTEGER, 0, MPI_COMM_WORLD, IERR)  
    call random_seed(put=myid*seed) ! set current seed

    


  end subroutine init_wave 

end module m_wave